/**
 * @author Lucas Balda
 */

#ifndef UICONFIG_H
#define UICONFIG_H

#include <lvgl.h>

#define SCREEN_WIDTH (480)
#define SCREEN_HEIGHT (320)

LV_IMG_DECLARE(heart_image)
LV_IMG_DECLARE(depth_image)
LV_IMG_DECLARE(lungs_image)
LV_IMG_DECLARE(sandclock_image)

LV_FONT_DECLARE(digital_numbers_40px)

#define THEME_PRIMARY_COLOR_NORMAL lv_color_make(210, 110, 0)
#define THEME_PRIMARY_COLOR_BRIGHT lv_color_mix(THEME_PRIMARY_COLOR_NORMAL, LV_COLOR_WHITE, 255 * 0.5)
#define THEME_PRIMARY_COLOR_DARK lv_color_mix(THEME_PRIMARY_COLOR_NORMAL, LV_COLOR_BLACK, 255 * 0.5)
#define THEME_PRIMARY_COLOR_BRIGHTER lv_color_mix(THEME_PRIMARY_COLOR_NORMAL, LV_COLOR_WHITE, 255 * 0.25)
#define THEME_PRIMARY_COLOR_DARKER lv_color_mix(THEME_PRIMARY_COLOR_NORMAL, LV_COLOR_BLACK, 255 * 0.25)

#define THEME_SECONDARY_COLOR_NORMAL lv_color_make(91, 91, 91)
#define THEME_SECONDARY_COLOR_BRIGHT lv_color_mix(THEME_SECONDARY_COLOR_NORMAL, LV_COLOR_WHITE, 255 * 0.5)
#define THEME_SECONDARY_COLOR_DARK lv_color_mix(THEME_SECONDARY_COLOR_NORMAL, LV_COLOR_BLACK, 255 * 0.5)
#define THEME_SECONDARY_COLOR_BRIGHTER lv_color_mix(THEME_SECONDARY_COLOR_NORMAL, LV_COLOR_WHITE, 255 * 0.25)
#define THEME_SECONDARY_COLOR_DARKER lv_color_mix(THEME_SECONDARY_COLOR_NORMAL, LV_COLOR_BLACK, 255 * 0.25)

#endif